config/routes.rb
Rails.application.routes.draw do
 devise_for :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root to: 'devise/sessions#new'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  get '/about', to: 'pages#about'
  get '/trash', to: 'pages#trash'
  match '/posts/trashposts/:id' => 'posts#trashposts', :via => [:get,:delete, :post], :as => :trashposts
  match '/comments/comment_trash/:id' => 'comments#comment_trash', :via => [:get,:delete, :post], :as => :comment_trash
  match '/posts/restore/:id' => 'posts#restore', :via => [:get,:delete, :post], :as => :restore
  match '/comments/comment_restore/:id' => 'comments#comment_restore', :via => [:get,:delete, :post], :as => :comment_restore
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord
	
  belongs_to :post
  scope :active_comments, lambda {where(:status => "Active")}

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  layout :layout_by_resource
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
	  about_path
  end

  def layout_by_resource
    if (params[:controller] == "pages" or params[:controller] == "comments" or params[:controller] == "posts")
      "site"
    else
      "application"
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_comment, only: [:create, :destroy]
  before_action :find_post, only:[:comment_trash,:comment_restore]

  def create
    @comment = @post.comments.create(params[:comment].permit(:user_name, :content))
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def comment_trash
    @comment.update_attributes(:status => "Deleted")
    respond_to do |format|
     format.html { redirect_to post_path(@post.id), notice: 'Trashed.' }
     format.json { head :no_content }
    end
  end

  def comment_restore
    @comment.update_attributes(:status => "Active")
    respond_to do |format|
     format.html { redirect_to post_path(@post.id), notice: 'Restored.' }
     format.json { head :no_content }
    end
  end


  private 

  def set_comment
    @post = Post.find(params[:post_id])
  end

  def find_post
    @post =  Comment.find(params[:id]).post
    @comment = @post.comments.find(params[:id]) 
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def trash
  	@posts = Post.where(:status => "Deleted").includes(:comments)
  	@comments = Comment.where(:status => "Deleted")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_post, only: [:edit, :update, :show, :destroy]


  def index
    @posts = Post.where(:status => "Active").includes(:comments).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy

    redirect_to root_path
  end

  def trashposts
    @post = Post.where(:id => params[:id]).first
    @post.update_attributes(:status => "Deleted")
    respond_to do |format|
     format.html { redirect_to posts_path, notice: 'Trashed.' }
     format.json { head :no_content }
    end
  end

  def restore
    @post = Post.where(:id => params[:id]).first
    @post.update_attributes(:status => "Active")
    respond_to do |format|
     format.html { redirect_to post_path(@post.id), notice: 'Post Restored.' }
     format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end


    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment_content
    %p.comment_name
      %strong= comment.user_name
    %p.comment_body= comment.content
    %p.comment_time
      = time_ago_in_words(comment.created_at)
      Ago
  - if user_signed_in?
    %p
      = link_to 'Delete', [comment.post, comment], |
        method: :delete,                           |
        class: "button",                           |
        data: { confirm: 'Are you sure?' }         |
    %p
      = link_to 'Trash', comment_trash_path(comment.id),class: "button"

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|
  = f.label :user_name
  %br/
  = f.text_field :user_name
  %br/
  %br/
  = f.label :content
  %br/
  = f.text_area :content
  %br/
  %br/
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CommentBox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Google Fonts
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    / Favicon
    / assets/images/favicon.ico
    = favicon_link_tag 'favicon.ico'
  %body
    #sidebar
      #logo
        = link_to root_path do
          = image_tag "logo.jpg"
    #main_content
      / Flash Message
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert")
      = yield

app/views/layouts/site.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CommentBox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Google Fonts
    = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
    / Favicon
    / assets/images/favicon.ico
    = favicon_link_tag 'favicon.ico'
  %body
    #sidebar
      #logo
        = link_to root_path do
          = image_tag "logo.jpg"
      %ul
        %li.category Posts Section
        %li= link_to "About", about_path
        %li= link_to "Posts", posts_path
        %li= link_to "Trash", trash_path
      - if !user_signed_in?
        %p.sign_in= link_to "Admin Login", new_user_session_path
    #main_content
      #header
        / Header Nav
        - if current_page?(posts_path)
          %p All Posts
        - elsif current_page?(about_path)
          %p About
        - else
          = link_to "Back to All Posts", posts_path
        / Header Link Buttons
        - if user_signed_in?
          .buttons
            %button.button= link_to "New Post", new_post_path
            %button.button= link_to('Logout', destroy_user_session_path, :method => :delete)
      / Flash Message
      - flash.each do |name, msg|
        = content_tag(:div, msg, class: "alert")
      = yield

app/views/pages/about.html.haml
/ About Page
#page_wrapper
  #profile_image
    = image_tag "profile.jpg"
  #content
    %h1 Welcome.
    %p Create some interesting posts !!!

app/views/pages/trash.html.haml
/ Post Index Page
- @posts.each do |post|
  .post_wrapper
    %h2.title= link_to post.title, post
    %p.date
      = post.created_at.strftime("%B %d, %Y")
      - if user_signed_in?
        = link_to 'Restore', restore_path(post.id), |
          class: "button"                           |
- @comments.each do |post|
  .post_wrapper
    %h2.title= link_to post.content
    %p.date
      = post.created_at.strftime("%B %d, %Y")
      - if user_signed_in?
        = link_to 'Restore', comment_restore_path(post.id), |
          class: "button"                                   |

app/views/posts/_form.html.haml
/ Form for a Post
= form_for @post do |f|
  - if @post.errors.any?
    #errors
      %h2
        = pluralize(@post.errors.count, "error")
        prevented this post from saving:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :body
    %br/
    = f.text_area :body
  %p
    = f.submit

app/views/posts/edit.html.haml
/ Edit Show Page
#page_wrapper
  %h1 Edit Post
  = render 'form'

app/views/posts/index.html.haml
/ Post Index Page
- @posts.each do |post|
  .post_wrapper
    %h2.title= link_to post.title, post
    %p.date= post.created_at.strftime("%B %d, %Y")
    %p= link_to 'View', post_path(post.id),class: "button"

app/views/posts/new.html.haml
/ New Post Page
#page_wrapper
  %h1 New Post
  = render 'form'

app/views/posts/show.html.haml
/ Post Show Page
#post_content
  %h1.title
    = @post.title
  %p.date
    Submitted #{time_ago_in_words(@post.created_at)} Ago
    - if user_signed_in?
      |#{link_to 'Edit', edit_post_path(@post),class: "button"} |
      #{link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' },class: "button"} |
      #{link_to 'Trash', trashposts_path(@post.id),class: "button"}
  %p.body= @post.body
  / Post Show Page
  #comments
    / Show Comments
    %h2
      = @post.comments.active_comments.count
      Comments
    = render @post.comments.active_comments
    / New Comment
    %h3 Add a comment:
    = render "comments/form"